Generic caller
Thetta/Thetta-DAO-Framework pull request #361
Opened 2018-10-30 04:29 UTC by enkogu

2018-10-30 08:02 UTC, AnthonyAkentiev approved these changes

2018-10-31 12:55 UTC, AnthonyAkentiev requested changes

2018-10-31 12:55 UTC, AnthonyAkentiev commented on contracts/utils/GenericCallerLib.sol
> +			bytes32[] storage params;
почему нельзя использовать _params?
зачем нужно заводить params?

2018-10-31 12:55 UTC, AnthonyAkentiev commented on contracts/utils/GenericCallerLib.sol
> +			params.push(bytes32(address(0))); // last param is always voting; in this case no voting created
Немного не понял.
Здесь идет только прямой вызов метода (никакого proposal'а не создается)

Не вижу ссылку на голосование для случая, когда создается пропозал

2018-10-31 12:57 UTC, enkogu commented on contracts/utils/GenericCallerLib.sol
> +			bytes32[] storage params;
Потому что нельзя пушить в bytes32[] memory

2018-10-31 12:57 UTC, AnthonyAkentiev commented on contracts/utils/GenericCallerLib.sol
> +			params.push(bytes32(address(0))); // last param is always voting; in this case no voting created
вот здесь идет вызов конечного метода из proposal'а - https://github.com/Thetta/Thetta-DAO-Framework/blob/master/contracts/governance/GenericProposal.sol#L37

тут нужно передавать дополнительно 1 параметр - голосование

2018-10-31 13:05 UTC, AnthonyAkentiev approved these changes

2018-10-31 13:06 UTC, merged